<!DOCTYPE html>
<html>
  <head>
    <title>ExtraCredit2 RecipeBook</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" type="text/css" href="/assets/css/styles.css" />
  </head>
<body class="container d-flex flex-column justify-content-center align-items-center vh-100">
	<h1 class="display-1 fw-bold">404</h1>
	<h3 class="mb-3">Page Not Found</h3>
	
	<p class="text-secondary mb-3">Sorry! Looks like the page you requested does not exist</p>
	
	<a href="/" class="btn btn-success">Go Back</a>

</body>
</html>